#!/bin/zsh
set -euo pipefail

APP_SUPPORT="{{APP_SUPPORT}}"
WORKSPACE="{{WORKSPACE}}"
NANOBOT="{{NANOBOT}}"
CONFIG="$APP_SUPPORT/nanobot/config.json"
LOG_DIR="$HOME/Library/Logs/UsefulAIAgent"

mkdir -p "$LOG_DIR"
cd "$WORKSPACE"

export NANOBOT_GUEST_REPLY_MODE="${NANOBOT_GUEST_REPLY_MODE:-placeholder}"
export NANOBOT_GUEST_PLACEHOLDER_TEXT="${NANOBOT_GUEST_PLACEHOLDER_TEXT:-⚡}"
export NANOBOT_GUEST_CUSTOM_EMOJI_MARKER="${NANOBOT_GUEST_CUSTOM_EMOJI_MARKER:-⚡}"
export NANOBOT_GUEST_CUSTOM_EMOJI_ID_FILE="${NANOBOT_GUEST_CUSTOM_EMOJI_ID_FILE:-$APP_SUPPORT/nanobot/guest-custom-emoji-id}"

exec "$NANOBOT" gateway --config "$CONFIG" >> "$LOG_DIR/nanobot.log" 2>&1
