#!/bin/zsh
set -euo pipefail

APP_SUPPORT="{{APP_SUPPORT}}"
WORKSPACE="{{WORKSPACE}}"
NANOBOT="{{NANOBOT}}"
CONFIG="$APP_SUPPORT/nanobot/config.json"
LOG_DIR="$HOME/Library/Logs/UsefulAIAgent"

mkdir -p "$LOG_DIR"
cd "$WORKSPACE"

export NANOBOT_GUEST_REPLY_MODE="${NANOBOT_GUEST_REPLY_MODE:-placeholder}"
export NANOBOT_GUEST_PLACEHOLDER_TEXT="${NANOBOT_GUEST_PLACEHOLDER_TEXT:-⚡}"
export NANOBOT_GUEST_CUSTOM_EMOJI_MARKER="${NANOBOT_GUEST_CUSTOM_EMOJI_MARKER:-⚡}"
export NANOBOT_GUEST_CUSTOM_EMOJI_ID_FILE="${NANOBOT_GUEST_CUSTOM_EMOJI_ID_FILE:-$APP_SUPPORT/nanobot/guest-custom-emoji-id}"
export CODEX_HOME="${CODEX_HOME:-$HOME/.codex}"
if [ -z "${NANOBOT_CODEX_CLI:-}" ]; then
  CODEX_BIN="$(command -v codex || true)"
  if [ -n "$CODEX_BIN" ]; then
    export NANOBOT_CODEX_CLI="$CODEX_BIN"
  fi
fi
export NANOBOT_CODEX_IMAGEGEN_WORKDIR="${NANOBOT_CODEX_IMAGEGEN_WORKDIR:-$WORKSPACE}"
export NANOBOT_CODEX_IMAGEGEN_TIMEOUT="${NANOBOT_CODEX_IMAGEGEN_TIMEOUT:-900}"
export NANOBOT_IMAGEGEN_DEFAULT_ASPECT_RATIO="${NANOBOT_IMAGEGEN_DEFAULT_ASPECT_RATIO:-4:5}"
export NANOBOT_IMAGEGEN_DEFAULT_SIZE="${NANOBOT_IMAGEGEN_DEFAULT_SIZE:-1K}"

exec "$NANOBOT" gateway --config "$CONFIG" >> "$LOG_DIR/nanobot.log" 2>&1
